function createfigure_34years(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Jul-2020 09:57:43

% Create figure
figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Position',[0.13 0.11 0.849476291578202 0.869089790897909]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(2),'Color',[1 0.843137264251709 0]);
set(plot1(3),'Color',[0 0.498039215803146 0]);
set(plot1(4),'LineWidth',2,'Color',[0 1 1]);
set(plot1(5),'LineStyle','--','Color',[0 0 0]);

% Create ylabel
ylabel('Transformer loading, pu');

% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16);
